import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

// The picker has no renderer in this suite, so its contract is asserted against
// the component source, in the same style as the other component tests. The
// keyboard decision table itself is covered by voiceNavigation.test.js.
const pickerSource = readFileSync(new URL("./PresetVoicePicker.jsx", import.meta.url), "utf8");

test("the picker is searchable, grouped and labelled from the catalog", () => {
  assert.match(pickerSource, /from "\.\.\/\.\.\/lib\/audio\/presetVoices\.js"/);
  assert.match(pickerSource, /listPresetVoices\(schema\)/);
  assert.match(pickerSource, /searchPresetVoices\(voices, query\)/);
  assert.match(pickerSource, /groupPresetVoices\(matches\)/);
  // Search by name or by the exact provider ID.
  assert.match(pickerSource, /Search \$\{voices\.length\} voices by name or ID…/);
  assert.match(pickerSource, /role="group"/);
  assert.match(pickerSource, /aria-label=\{`\$\{group\.label\}, \$\{group\.voices\.length\} voices`\}/);
});

test("the search field is a combobox that owns the listbox", () => {
  assert.match(pickerSource, /from "\.\.\/\.\.\/lib\/audio\/voiceNavigation\.js"/);
  assert.match(pickerSource, /role="combobox"/);
  assert.match(pickerSource, /aria-expanded="true"/);
  assert.match(pickerSource, /aria-controls=\{listboxId\}/);
  assert.match(pickerSource, /aria-activedescendant=\{activeOptionId\}/);
  assert.match(pickerSource, /aria-autocomplete="list"/);
  // Labelled by the field name and described by the result count.
  assert.match(pickerSource, /aria-labelledby=\{labelId\}/);
  assert.match(pickerSource, /aria-describedby=\{statusId\}/);
  assert.match(pickerSource, /role="listbox"/);
  assert.match(pickerSource, /aria-label=\{`\$\{label\} options`\}/);
  // Ids are generated by React, never randomly, so markup is stable per render.
  assert.match(pickerSource, /const baseId = useId\(\);/);
  assert.doesNotMatch(pickerSource, /Math\.random\(\)/);
});

test("voices are options whose selected state is exposed", () => {
  assert.match(pickerSource, /role="option"/);
  assert.match(pickerSource, /aria-selected=\{isSelected\}/);
  assert.match(pickerSource, /id=\{optionDomId\(listboxId, index\)\}/);
  // The active option is marked for the scroll effect, and its id is what
  // aria-activedescendant points at.
  assert.match(pickerSource, /data-active=\{isActive \? "true" : undefined\}/);
  assert.match(
    pickerSource,
    /const activeOptionId = activeVoice \? optionDomId\(listboxId, activeIndex\) : undefined;/,
  );
  // Options are reached through the search field, never by tabbing through 472
  // controls.
  assert.doesNotMatch(pickerSource, /role="option"[\s\S]{0,400}?tabIndex/);
});

test("the arrow and Enter keys are wired to the navigation table", () => {
  assert.match(
    pickerSource,
    /resolveVoiceKeyAction\(\{ key: event\.key, count, activeIndex \}\)/,
  );
  assert.match(pickerSource, /action\.type === VOICE_KEY_ACTION_TYPES\.MOVE/);
  assert.match(pickerSource, /setActiveIndex\(action\.index\)/);
  assert.match(pickerSource, /action\.type === VOICE_KEY_ACTION_TYPES\.SELECT && activeVoice/);
  assert.match(pickerSource, /select\(activeVoice\)/);
  // Arrowing and Entering must not scroll the page or submit a form.
  assert.match(pickerSource, /event\.preventDefault\(\)/);
});

test("Escape closes from anywhere inside the picker, but other keys stay with the field", () => {
  const closeAt = pickerSource.indexOf("action.type === VOICE_KEY_ACTION_TYPES.CLOSE");
  const guardAt = pickerSource.indexOf("if (event.target !== searchRef.current) return;");
  assert.ok(closeAt !== -1, "expected the close branch");
  assert.ok(guardAt !== -1, "expected the search-field guard");
  // Escape is handled before the guard, so it works from the Clear button too;
  // Enter after the guard, so pressing it on Clear still clears the query.
  assert.ok(closeAt < guardAt, "Escape must be handled before the field guard");
  assert.match(pickerSource, /onKeyDown=\{handleListKeyDown\}/);
});

test("focus moves into the field on open and back to the control on close", () => {
  assert.match(pickerSource, /searchRef\.current\?\.focus\(\);/);
  assert.match(pickerSource, /triggerRef\.current\?\.focus\(\);/);
  assert.match(pickerSource, /const closeAndRestoreFocus = \(\) => \{/);
  // Selecting also restores focus, so it never falls to the document.
  const selectAt = pickerSource.indexOf("const select = (voice) => {");
  assert.ok(pickerSource.slice(selectAt, selectAt + 160).includes("closeAndRestoreFocus()"));
  // The trigger advertises the popup and opens on the listbox arrow keys.
  assert.match(pickerSource, /aria-haspopup="listbox"/);
  assert.match(pickerSource, /aria-expanded=\{open\}/);
  assert.match(pickerSource, /event\.key !== "ArrowDown" && event\.key !== "ArrowUp"/);
  // The active option is kept in view while arrowing.
  assert.match(pickerSource, /querySelector\('\[data-active="true"\]'\)/);
});

test("results and the current selection stay understandable to assistive technology", () => {
  // A polite live region announces the result count as the query narrows.
  assert.match(pickerSource, /id=\{statusId\}/);
  assert.match(pickerSource, /role="status"/);
  assert.match(pickerSource, /\$\{count\} of \$\{voices\.length\} voices/);
  // Group headers are decorative: the group's own accessible name carries the
  // text and the count, so nothing is announced twice, and the header is not an
  // option.
  assert.match(
    pickerSource,
    /<div\s+aria-hidden="true"\s+className="flex items-center gap-2 px-3 py-2[^"]*"\s*>/,
  );
  assert.doesNotMatch(pickerSource, /aria-hidden="true"[\s\S]{0,120}?role="option"/);
});

test("every group is expanded: no voice is hidden behind a disclosure", () => {
  // Collapsible headers were removed so the listbox contains nothing but
  // options and navigation reaches every visible voice.
  assert.doesNotMatch(pickerSource, /toggleGroup/);
  assert.doesNotMatch(pickerSource, /isExpanded/);
  assert.doesNotMatch(pickerSource, /aria-expanded=\{expanded\}/);
});

test("the picker writes back the exact catalog ID and shows it", () => {
  assert.match(pickerSource, /const select = \(voice\) => \{\s+onChange\(voice\.id\);/);
  // Exactly one write path, and it writes the selected voice's own ID — never a
  // normalised, renamed or resolved value.
  assert.equal((pickerSource.match(/onChange\(/g) || []).length, 1);
  assert.match(pickerSource, /\{voice\.id\}/);
});

test("built-in voices are visibly distinct from custom voice IDs", () => {
  assert.match(pickerSource, /Built-in voice · \$\{selected\.id\}/);
  assert.match(pickerSource, /Custom voice ID · \$\{selected\.id\}/);
  assert.match(pickerSource, /\{voice\.isCustomId \? "Custom voice ID · " : ""\}/);
  assert.match(pickerSource, /CUSTOM_VOICE_GROUP/);
});

test("no voice preview is fabricated and no call is made automatically", () => {
  // The catalog carries no sample URLs, so auditioning would require a paid
  // generation call. The picker ships without either.
  assert.doesNotMatch(pickerSource, /<audio/);
  assert.doesNotMatch(pickerSource, /new Audio\(/);
  assert.doesNotMatch(pickerSource, /fetch\(/);
  assert.doesNotMatch(pickerSource, /previewUrl|sampleUrl|audioUrl/);
});

test("the picker closes on an outside click and resets its query", () => {
  assert.match(pickerSource, /window\.addEventListener\("mousedown", handlePointer\)/);
  assert.match(pickerSource, /if \(!open\) setQuery\(""\);/);
});
