CREATE TABLE IF NOT EXISTS creative_jobs (
  job_id VARCHAR(191) NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  creator_identity_key VARCHAR(191) NOT NULL,
  authorization_id VARCHAR(191) NOT NULL,
  request_id VARCHAR(191) NOT NULL,
  idempotency_key VARCHAR(191) NULL,
  agent_id VARCHAR(191) NOT NULL,
  conversation_id VARCHAR(191) NOT NULL,
  campaign_id VARCHAR(191) NULL,
  twin_context_json JSON NULL,
  plan_id VARCHAR(191) NULL,
  asset_request_id VARCHAR(191) NULL,
  recipe_id VARCHAR(191) NULL,
  recipe_json JSON NULL,
  operation VARCHAR(191) NOT NULL,
  execution_status VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  priority VARCHAR(32) NOT NULL DEFAULT 'normal',
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  execution_context_id VARCHAR(191) NULL,
  execution_context_json JSON NOT NULL,
  plan_json JSON NULL,
  result_json JSON NULL,
  error_json JSON NULL,
  metadata_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (job_id),
  UNIQUE KEY uq_creative_jobs_authorization_id (authorization_id),
  UNIQUE KEY uq_creative_jobs_account_idempotency (account_id, idempotency_key),
  KEY idx_creative_jobs_account_status (account_id, status, updated_at),
  KEY idx_creative_jobs_account_creator (account_id, creator_identity_key, created_at),
  KEY idx_creative_jobs_campaign (account_id, campaign_id, created_at),
  KEY idx_creative_jobs_request (account_id, request_id),
  CONSTRAINT chk_creative_jobs_attempt_count CHECK (attempt_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
