CREATE TABLE IF NOT EXISTS creative_assets (
  asset_id VARCHAR(191) NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  creator_identity_key VARCHAR(191) NOT NULL,
  job_id VARCHAR(191) NOT NULL,
  attempt_id VARCHAR(191) NOT NULL,
  request_id VARCHAR(191) NOT NULL,
  authorization_id VARCHAR(191) NOT NULL,
  agent_id VARCHAR(191) NOT NULL,
  conversation_id VARCHAR(191) NOT NULL,
  campaign_id VARCHAR(191) NULL,
  asset_type VARCHAR(64) NOT NULL,
  modality VARCHAR(64) NULL,
  provider_id VARCHAR(191) NULL,
  deployment_id VARCHAR(191) NULL,
  provider_output_ref VARCHAR(1024) NULL,
  storage_reference VARCHAR(1024) NULL,
  recipe_id VARCHAR(191) NULL,
  plan_id VARCHAR(191) NULL,
  asset_json JSON NOT NULL,
  metadata_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (asset_id),
  UNIQUE KEY uq_creative_assets_execution (job_id, attempt_id),
  KEY idx_creative_assets_account_creator (account_id, creator_identity_key, created_at),
  KEY idx_creative_assets_campaign (account_id, campaign_id, created_at),
  KEY idx_creative_assets_request (account_id, request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
