import {
  APERTURE_EFFECT,
  CAMERA_MAP,
  FOCAL_PERSPECTIVE,
  LENS_MAP,
} from "./vocabulary.js";

export const PROVIDER_CONFIG = Object.freeze({
  muapi: Object.freeze({ id: "muapi", name: "MuAPI", enabled: true }),
});

export const PROMPT_LIBRARY = Object.freeze({
  cinematic: Object.freeze({
    id: "cinematic",
    version: 1,
    parts: ({ prompt, camera, lens, focalLength, aperture }) => [
      prompt,
      `shot on a ${CAMERA_MAP[camera] || camera}`,
      `using a ${LENS_MAP[lens] || lens} at ${focalLength}mm ${FOCAL_PERSPECTIVE[focalLength] ? `(${FOCAL_PERSPECTIVE[focalLength]})` : ""}`,
      `aperture ${aperture}`,
      APERTURE_EFFECT[aperture],
      "cinematic lighting",
      "natural color science",
      "high dynamic range",
      "professional photography, ultra-detailed, 8K resolution",
    ],
  }),
  plain: Object.freeze({
    id: "plain",
    version: 1,
    parts: ({ prompt }) => [prompt],
  }),
});

export const RECIPE_LIBRARY = Object.freeze({
  cinemaImage: Object.freeze({
    id: "cinema-image",
    promptId: "cinematic",
    providerId: "muapi",
    model: ({ reference }) => reference ? "nano-banana-pro-edit" : "nano-banana-pro",
    defaults: Object.freeze({ negative_prompt: "blurry, low quality, distortion, bad composition" }),
  }),
  image: Object.freeze({
    id: "image",
    promptId: "plain",
    providerId: "muapi",
    capabilityRequirements: ["image_generation"],
  }),
  marketing: Object.freeze({
    id: "marketing",
    promptId: "plain",
    providerId: "muapi",
  }),
  video: Object.freeze({
    id: "video",
    promptId: "plain",
    providerId: "muapi",
    capabilityRequirements: ["video_generation"],
  }),
  imageEdit: Object.freeze({
    id: "image-edit",
    promptId: "plain",
    providerId: "muapi",
    capabilityRequirements: ["image_editing"],
  }),
  aiInfluencer: Object.freeze({
    id: "ai-influencer",
    promptId: "aiInfluencer",
    providerId: "muapi",
    model: "nano-banana-pro",
    capabilityRequirements: ["image_generation", "reference_images", "character_consistency"],
  }),
  vibeMotion: Object.freeze({
    id: "vibe-motion",
    promptId: "plain",
    providerId: "muapi",
    capabilityRequirements: ["video_generation"],
  }),
  audio: Object.freeze({
    id: "audio",
    promptId: "plain",
    providerId: "muapi",
    capabilityRequirements: ["voice_generation"],
  }),
  recast: Object.freeze({
    id: "recast",
    promptId: "plain",
    providerId: "muapi",
    capabilityRequirements: ["video_editing"],
  }),
  lipSync: Object.freeze({
    id: "lip-sync",
    promptId: "plain",
    providerId: "muapi",
    capabilityRequirements: ["lip_sync"],
  }),
  videoTransform: Object.freeze({
    id: "video-transform",
    promptId: "plain",
    providerId: "muapi",
    capabilityRequirements: ["video_editing"],
  }),
  repurposeVideo: Object.freeze({
    id: "repurposeVideo",
    name: "Repurpose long-form video into short-form clips",
    promptId: "plain",
    providerId: "muapi",
    skillId: "ai-clipping",
    operation: "ai_clipping",
    outputModality: "video",
    outputSubtype: "short-form clip",
    capabilityRequirements: ["video_editing", "highlight_extraction"],
    inputs: Object.freeze({
      videoUrl: { type: "string", required: true, description: "Source video URL or canonical source asset URL" },
      sourceAssetId: { type: "string", required: false, description: "Canonical source Creative Asset id (lineage)" },
      numHighlights: { type: "number", required: false, default: 3, description: "Maximum number of highlights/clips" },
      aspectRatio: { type: "string", required: false, default: "9:16", description: "Short-form aspect ratio" },
      coordinatesOnly: { type: "boolean", required: false, default: false, description: "Return highlight coordinates instead of rendered clips" },
      guidance: { type: "string", required: false, description: "Optional clipping guidance / hook notes" },
    }),
    outputs: Object.freeze({
      clips: { type: "array", description: "Normalized clips (url, title, startTime, endTime, duration, score, hook, viralityReason, aspectRatio)" },
      coordinates: { type: "array", description: "Optional highlight coordinates for coordinate-only review" },
      requestId: { type: "string", description: "Provider request id" },
      sourceVideoUrl: { type: "string", description: "Source video used by the provider" },
    }),
    metadata: Object.freeze({
      sourceAssetId: { description: "Canonical source asset id (lineage)" },
      campaignId: { description: "Active campaign id" },
      twinId: { description: "Selected AI Twin id" },
      agentId: { description: "Initiating Agent id" },
      workspace: { description: "Initiating workspace (video / agents / ai-twin / command-bar)" },
      provider: { description: "Provider id (chosen by recipe/config, never the Command Bar)" },
      recipeId: { description: "Recipe id" },
      skillId: { description: "Skill id (ai-clipping)" },
    }),
  }),
  motionGraphics: Object.freeze({
    id: "motionGraphics",
    name: "Render a motion graphic from a workflow template",
    promptId: "plain",
    providerId: "muapi",
    skillId: "vibe-motion",
    operation: "motion_graphics",
    outputModality: "video",
    outputSubtype: "motion graphic",
    capabilityRequirements: ["motion_graphics"],
    inputs: Object.freeze({
      templateId: { type: "string", required: true, description: "Workflow template id (logo-reveal, countdown-timer, ...)" },
      text: { type: "string", required: false, description: "Primary text/headline animated by the template" },
      brandColors: { type: "array", required: false, description: "Brand color palette applied to the graphic" },
      logo: { type: "string", required: false, description: "Logo image URL to animate" },
      images: { type: "array", required: false, description: "Reference/product image URLs used by the template" },
      durationSeconds: { type: "number", required: false, description: "Animation duration in seconds" },
      aspectRatio: { type: "string", required: false, description: "Output aspect ratio (16:9, 9:16, 1:1)" },
      prompt: { type: "string", required: false, description: "Optional prompt refinement layered over the template" },
    }),
    outputs: Object.freeze({
      video: { type: "string", description: "Rendered motion graphic video URL" },
      preview: { type: "string", description: "Optional preview URL" },
      requestId: { type: "string", description: "Provider request id" },
      providerMetadata: { type: "object", description: "Preserved provider response fields" },
    }),
    metadata: Object.freeze({
      templateId: { description: "Workflow template id" },
      skillId: { description: "Creative skill id (vibe-motion)" },
      recipeId: { description: "Recipe id" },
      provider: { description: "Provider id (chosen by recipe/config, never the Command Bar)" },
      campaignId: { description: "Active campaign id" },
      twinId: { description: "Selected AI Twin id" },
      agentId: { description: "Initiating Agent id" },
      workspace: { description: "Initiating workspace (marketing / agents / ai-twin / command-bar)" },
      durationSeconds: { description: "Rendered duration in seconds" },
      aspectRatio: { description: "Rendered aspect ratio" },
    }),
  }),
  performanceTransfer: Object.freeze({
    id: "performanceTransfer",
    name: "Transfer a driving performance onto a character identity",
    promptId: "plain",
    providerId: "muapi",
    skillId: "recast",
    operation: "performance_transfer",
    outputModality: "video",
    outputSubtype: "performance transfer",
    capabilityRequirements: ["performance_transfer", "identity_preservation", "motion_transfer", "character_consistency"],
    inputs: Object.freeze({
      characterImage: { type: "string", required: true, description: "Character identity image URL (AI Influencer identity, AI Twin likeness, or temporary upload)" },
      drivingVideo: { type: "string", required: true, description: "Driving video URL whose performance/motion is transferred onto the character" },
      characterIdentity: { type: "object", required: false, description: "Character identity source metadata { id, type, name, imageUrl }" },
      sourceAssetId: { type: "string", required: false, description: "Canonical source Creative Asset id (lineage)" },
      model: { type: "string", required: false, description: "Model-specific parameter (recast model id)" },
      aspectRatio: { type: "string", required: false, description: "Output aspect ratio (model-dependent)" },
      characterOrientation: { type: "string", required: false, description: "Model-specific orientation (image / video)" },
      prompt: { type: "string", required: false, description: "Optional prompt refinement for the transfer" },
    }),
    outputs: Object.freeze({
      video: { type: "string", description: "Rendered performance transfer video URL" },
      requestId: { type: "string", description: "Provider request id" },
      providerMetadata: { type: "object", description: "Preserved provider response fields" },
    }),
    metadata: Object.freeze({
      characterIdentity: { description: "Character identity source { id, type, name, imageUrl }" },
      sourceAssetId: { description: "Canonical source asset id (lineage)" },
      campaignId: { description: "Active campaign id" },
      twinId: { description: "Selected AI Twin id" },
      agentId: { description: "Initiating Agent id" },
      workspace: { description: "Initiating workspace (character / agents / ai-twin / command-bar)" },
      provider: { description: "Provider id (chosen by recipe/config, never the Command Bar)" },
      recipeId: { description: "Recipe id" },
      skillId: { description: "Skill id (recast)" },
    }),
  }),
  workflow: Object.freeze({
    id: "workflow",
    promptId: "plain",
    providerId: "muapi-workflow",
  }),
});