export function createCreativePlan(input = {}) {
  return {
    planId: input.planId || null,
    request: input.request || null,
    agent: input.agent || null,
    recipe: input.recipe || null,
    workflow: input.workflow || null,
    selectedSkills: Array.isArray(input.selectedSkills) ? [...input.selectedSkills] : [],
    skillSelectionReasons: Array.isArray(input.skillSelectionReasons) ? [...input.skillSelectionReasons] : [],
    compatibleContentTypes: Array.isArray(input.compatibleContentTypes) ? [...input.compatibleContentTypes] : [],
    compatibleCampaignTemplates: Array.isArray(input.compatibleCampaignTemplates) ? [...input.compatibleCampaignTemplates] : [],
    contextReferences: Array.isArray(input.contextReferences) ? [...input.contextReferences] : [],
    campaignContext: input.campaignContext || null,
    memoryReferences: Array.isArray(input.memoryReferences) ? [...input.memoryReferences] : [],
    memoryProjection: input.memoryProjection || null,
    knowledgeContext: input.knowledgeContext || null,
    capabilityRequirements: Array.isArray(input.capabilityRequirements) ? [...input.capabilityRequirements] : [],
    routing: input.routing || null,
    executionPlan: input.executionPlan || null,
    creativeSkills: input.creativeSkills || null,
    requiredInputs: Array.isArray(input.requiredInputs) ? [...input.requiredInputs] : [],
    unresolvedRequiredInputs: Array.isArray(input.unresolvedRequiredInputs) ? [...input.unresolvedRequiredInputs] : [],
    approvalRequirements: Array.isArray(input.approvalRequirements) ? [...input.approvalRequirements] : [],
    qaRequirements: Array.isArray(input.qaRequirements) ? [...input.qaRequirements] : [],
    retryRecovery: input.retryRecovery || null,
    costQualityStrategy: input.costQualityStrategy || null,
    provenance: Array.isArray(input.provenance) ? [...input.provenance] : [],
    state: input.state || (input.valid === false ? "non_executable" : "executable"),
    errors: Array.isArray(input.errors) ? [...input.errors] : [],
    warnings: Array.isArray(input.warnings) ? [...input.warnings] : [],
    assumptions: Array.isArray(input.assumptions) ? [...input.assumptions] : [],
    valid: input.valid !== false,
    createdAt: input.createdAt || new Date().toISOString(),
    metadata: input.metadata && typeof input.metadata === "object" ? { ...input.metadata } : {},
  };
}
