import { capabilityRegistry } from "./CapabilityRegistry.js";
import { providerCapabilityRegistry } from "./ProviderCapabilityRegistry.js";
import { CAPABILITIES } from "./CapabilityTypes.js";
import { PROVIDER_CONFIG } from "./config.js";

export const PRODUCTION_CAPABILITIES = Object.freeze([
  { id: CAPABILITIES.TEXT_GENERATION, name: "Text and LLM Generation", operation: "text_generation", inputModalities: ["text"], outputModalities: ["text"] },
  { id: CAPABILITIES.IMAGE_GENERATION, name: "Image Generation", operation: "image_generation", inputModalities: ["text"], outputModalities: ["image"] },
  { id: CAPABILITIES.IMAGE_EDITING, name: "Image Editing", operation: "image_editing", inputModalities: ["image", "text"], outputModalities: ["image"] },
  { id: CAPABILITIES.IMAGE_UPSCALING, name: "Image Upscaling", operation: "image_upscaling", inputModalities: ["image"], outputModalities: ["image"] },
  { id: CAPABILITIES.IMAGE_VARIATION, name: "Image Variation", operation: "image_variation", inputModalities: ["image", "text"], outputModalities: ["image"] },
  { id: CAPABILITIES.VIDEO_GENERATION, name: "Video Generation", operation: "video_generation", inputModalities: ["text"], outputModalities: ["video"] },
  { id: CAPABILITIES.VIDEO_EDITING, name: "Video Editing", operation: "video_editing", inputModalities: ["video"], outputModalities: ["video"] },
  { id: CAPABILITIES.LIP_SYNC, name: "Lip Sync", operation: "lip_sync", inputModalities: ["video", "audio"], outputModalities: ["video"] },
  { id: CAPABILITIES.VOICE_GENERATION, name: "Voice Generation", operation: "voice_generation", inputModalities: ["text"], outputModalities: ["audio"] },
  { id: CAPABILITIES.SPEECH_RECOGNITION, name: "Speech Recognition", operation: "speech_recognition", inputModalities: ["audio"], outputModalities: ["text"] },
  { id: CAPABILITIES.BACKGROUND_REMOVAL, name: "Background Removal", operation: "background_removal", inputModalities: ["image"], outputModalities: ["image"] },
  { id: CAPABILITIES.INPAINTING, name: "Inpainting", operation: "inpainting", inputModalities: ["image", "text"], outputModalities: ["image"] },
  { id: CAPABILITIES.OUTPAINTING, name: "Outpainting", operation: "outpainting", inputModalities: ["image", "text"], outputModalities: ["image"] },
  { id: CAPABILITIES.TYPOGRAPHY, name: "Typography", operation: "image_generation", inputModalities: ["text"], outputModalities: ["image"] },
  { id: CAPABILITIES.PHOTOREALISM, name: "Photorealism", operation: "image_generation", inputModalities: ["text"], outputModalities: ["image"] },
  { id: CAPABILITIES.REFERENCE_IMAGES, name: "Reference Images", operation: "image_editing", inputModalities: ["image", "text"], outputModalities: ["image"] },
  { id: CAPABILITIES.PROMPT_ENHANCEMENT, name: "Prompt Enhancement", operation: "prompt_enhancement", inputModalities: ["text"], outputModalities: ["text"] },
  { id: CAPABILITIES.LONG_FORM_VIDEO_ANALYSIS, name: "Long-Form Video Analysis", operation: "ai_clipping", inputModalities: ["video"], outputModalities: ["video"] },
  { id: CAPABILITIES.HIGHLIGHT_EXTRACTION, name: "Highlight Extraction", operation: "ai_clipping", inputModalities: ["video"], outputModalities: ["video"] },
  { id: CAPABILITIES.MOTION_GRAPHICS, name: "Motion Graphics", operation: "motion_graphics", inputModalities: ["text", "image"], outputModalities: ["video"] },
  { id: CAPABILITIES.MOTION_GRAPHICS_EDIT, name: "Motion Graphics Edit", operation: "motion_graphics_edit", inputModalities: ["text"], outputModalities: ["video"] },
  { id: CAPABILITIES.PERFORMANCE_TRANSFER, name: "Performance Transfer", operation: "performance_transfer", inputModalities: ["image", "video"], outputModalities: ["video"] },
  { id: CAPABILITIES.IDENTITY_PRESERVATION, name: "Identity Preservation", operation: "performance_transfer", inputModalities: ["image"], outputModalities: ["video"] },
  { id: CAPABILITIES.MOTION_TRANSFER, name: "Motion Transfer", operation: "performance_transfer", inputModalities: ["video"], outputModalities: ["video"] },
]);

export const PRODUCTION_DEPLOYMENTS = Object.freeze([
  {
    id: "openai-compatible-text",
    providerId: "openai",
    logicalModel: PROVIDER_CONFIG.openai.model,
    operation: "text_generation",
    capabilities: [CAPABILITIES.TEXT_GENERATION, CAPABILITIES.PROMPT_ENHANCEMENT],
    inputs: ["text"], outputs: ["text"], priority: 10, confidence: 0.8,
    featureState: "enabled", availability: "available", health: "healthy",
    quality: { standard: 0.8, premium: 0.9 }, speed: { tier: "standard" }, cost: { unit: "token", unitCost: null },
    license: { commercial: true }, supports: { streaming: true }, limits: {},
  },
  {
    id: "muapi-image-generation",
    providerId: "muapi",
    logicalModel: "muapi-image-catalog",
    operation: "image_generation",
    capabilities: [CAPABILITIES.IMAGE_GENERATION, CAPABILITIES.PHOTOREALISM, CAPABILITIES.COMMERCIAL_LICENSE],
    inputs: ["text"], outputs: ["image"], priority: 10, confidence: 0.8,
    featureState: "enabled", availability: "available", health: "healthy",
    quality: { standard: 0.8, premium: 0.9 }, speed: { tier: "standard" }, cost: { unit: "image", unitCost: null },
    license: { commercial: true }, supports: { asynchronous: true, polling: true, cancellation: false, batching: true },
    limits: { maxWidth: 4096, maxHeight: 4096 },
  },
  {
    id: "muapi-image-editing",
    providerId: "muapi",
    logicalModel: "muapi-image-edit-catalog",
    operation: "image_editing",
    capabilities: [CAPABILITIES.IMAGE_EDITING, CAPABILITIES.REFERENCE_IMAGES, CAPABILITIES.INPAINTING, CAPABILITIES.OUTPAINTING, CAPABILITIES.COMMERCIAL_LICENSE],
    inputs: ["image", "text"], outputs: ["image"], priority: 10, confidence: 0.8,
    featureState: "enabled", availability: "available", health: "healthy",
    quality: { standard: 0.8, premium: 0.9 }, speed: { tier: "standard" }, cost: { unit: "image", unitCost: null },
    license: { commercial: true }, supports: { asynchronous: true, polling: true, cancellation: false, referenceImages: true },
    limits: { maxReferenceImages: 14, maxWidth: 4096, maxHeight: 4096 },
  },
  {
    id: "muapi-ai-clipping",
    providerId: "muapi",
    logicalModel: "muapi-ai-clipping",
    operation: "ai_clipping",
    capabilities: [CAPABILITIES.VIDEO_EDITING, CAPABILITIES.LONG_FORM_VIDEO_ANALYSIS, CAPABILITIES.HIGHLIGHT_EXTRACTION, CAPABILITIES.COMMERCIAL_LICENSE],
    inputs: ["video", "text"], outputs: ["video"], priority: 10, confidence: 0.8,
    featureState: "enabled", availability: "available", health: "healthy",
    quality: { standard: 0.8, premium: 0.9 }, speed: { tier: "standard" }, cost: { unit: "clip", unitCost: null },
    license: { commercial: true }, supports: { asynchronous: true, polling: true, cancellation: false, multiAsset: true },
    limits: { maxHighlights: 60 },
  },
  {
    id: "muapi-motion-graphics",
    providerId: "muapi",
    logicalModel: "muapi-motion-graphics",
    operation: "motion_graphics",
    capabilities: [CAPABILITIES.MOTION_GRAPHICS, CAPABILITIES.MOTION_GRAPHICS_EDIT, CAPABILITIES.COMMERCIAL_LICENSE],
    inputs: ["text", "image"], outputs: ["video"], priority: 10, confidence: 0.8,
    featureState: "enabled", availability: "available", health: "healthy",
    quality: { standard: 0.8, premium: 0.9 }, speed: { tier: "standard" }, cost: { unit: "video", unitCost: null },
    license: { commercial: true }, supports: { asynchronous: true, polling: true, cancellation: false, edit: true },
    limits: { maxDurationSeconds: 30 },
  },
  {
    id: "muapi-performance-transfer",
    providerId: "muapi",
    logicalModel: "muapi-recast-catalog",
    operation: "performance_transfer",
    capabilities: [CAPABILITIES.PERFORMANCE_TRANSFER, CAPABILITIES.IDENTITY_PRESERVATION, CAPABILITIES.MOTION_TRANSFER, CAPABILITIES.CHARACTER_CONSISTENCY, CAPABILITIES.COMMERCIAL_LICENSE],
    inputs: ["image", "video", "text"], outputs: ["video"], priority: 10, confidence: 0.8,
    featureState: "enabled", availability: "available", health: "healthy",
    quality: { standard: 0.8, premium: 0.9 }, speed: { tier: "standard" }, cost: { unit: "video", unitCost: null },
    license: { commercial: true }, supports: { asynchronous: true, polling: true, cancellation: false, characterOrientation: true },
    limits: { maxDrivingSeconds: 30, maxReferenceImages: 1 },
  },
  {
    id: "muapi-video-generation",
    providerId: "muapi",
    logicalModel: "muapi-i2v-catalog",
    operation: "image_to_video",
    capabilities: [CAPABILITIES.VIDEO_GENERATION, CAPABILITIES.COMMERCIAL_LICENSE],
    inputs: ["image", "text"], outputs: ["video"], priority: 10, confidence: 0.8,
    featureState: "enabled", availability: "available", health: "healthy",
    quality: { standard: 0.8, premium: 0.9 }, speed: { tier: "standard" }, cost: { unit: "video", unitCost: null },
    license: { commercial: true }, supports: { asynchronous: true, polling: true, cancellation: false },
    limits: {},
  },
  {
    id: "muapi-lip-sync",
    providerId: "muapi",
    logicalModel: "muapi-lipsync-catalog",
    operation: "lip_sync",
    capabilities: [CAPABILITIES.LIP_SYNC, CAPABILITIES.COMMERCIAL_LICENSE],
    inputs: ["image", "video", "audio"], outputs: ["video"], priority: 10, confidence: 0.8,
    featureState: "enabled", availability: "available", health: "healthy",
    quality: { standard: 0.8, premium: 0.9 }, speed: { tier: "standard" }, cost: { unit: "video", unitCost: null },
    license: { commercial: true }, supports: { asynchronous: true, polling: true, cancellation: false },
    limits: {},
  },
]);

const MUAPI_CATALOG_SOURCE = Object.freeze({
  document: "MUAPI_MODEL_INTELLIGENCE_CATALOG.md",
  compiledAt: "2026-08-13",
  sourceType: "research-catalog",
});

const verified = (section, note = null) => ({
  status: "verified",
  section,
  ...(note ? { note } : {}),
});

// Representative model records only. These are stored alongside deployments,
// but are intentionally not deployments themselves yet, so routing behavior is
// unchanged while the normalized catalog contract is established.
export const MUAPI_MODEL_FIXTURES = Object.freeze([
  {
    id: "muapi-nano-banana-pro",
    providerId: "muapi",
    logicalFamily: "nano-banana",
    modelId: "nano-banana-pro",
    endpointId: "nano-banana-pro",
    operation: "image_generation",
    modality: "image",
    capabilities: [CAPABILITIES.IMAGE_GENERATION, CAPABILITIES.COMMERCIAL_LICENSE],
    tier: "pro",
    pricing: { currency: "USD", unit: "generation", unitPrice: null },
    source: MUAPI_CATALOG_SOURCE,
    verification: verified("Text-to-Image", "Canonical model identifier is present in the existing studio model registry."),
  },
  {
    id: "muapi-nano-banana-pro-edit",
    providerId: "muapi",
    logicalFamily: "nano-banana",
    modelId: "nano-banana-pro-edit",
    endpointId: "nano-banana-pro-edit",
    operation: "image_editing",
    modality: "image",
    capabilities: [CAPABILITIES.IMAGE_EDITING, CAPABILITIES.REFERENCE_IMAGES, CAPABILITIES.COMMERCIAL_LICENSE],
    tier: "pro",
    referenceLimits: { max: 8 },
    inputLimits: { required: ["image"] },
    pricing: { currency: "USD", unit: "generation", unitPrice: null },
    source: MUAPI_CATALOG_SOURCE,
    verification: verified("Image Editing", "Canonical reference-image model identifier is present in the existing studio model registry."),
  },
  {
    id: "muapi-tool-ai-background-remover",
    providerId: "muapi",
    logicalFamily: "ai-background-remover",
    modelId: "ai-background-remover",
    endpointId: "ai-background-remover",
    operation: "background_removal",
    modality: "image",
    capabilities: [CAPABILITIES.BACKGROUND_REMOVAL, CAPABILITIES.COMMERCIAL_LICENSE],
    tier: "specialist",
    variant: { purpose: "background-removal" },
    inputLimits: { required: ["image"] },
    pricing: { currency: "USD", unit: "generation", unitPrice: 0.01 },
    source: MUAPI_CATALOG_SOURCE,
    verification: verified("Product Photography & Background Removal"),
  },
  {
    id: "muapi-flux-kontext-dev-t2i",
    providerId: "muapi",
    logicalFamily: "flux-kontext-t2i",
    modelId: "flux-kontext-dev-t2i",
    endpointId: "flux-kontext-dev-t2i",
    operation: "image_generation",
    modality: "image",
    capabilities: [CAPABILITIES.IMAGE_GENERATION, CAPABILITIES.COMMERCIAL_LICENSE],
    tier: "dev",
    variant: { familyTier: "dev" },
    pricing: { currency: "USD", unit: "generation", unitPrice: 0.02 },
    source: MUAPI_CATALOG_SOURCE,
    verification: verified("Text-to-Image", "Flux Kontext tiers are represented as one logical family."),
  },
  {
    id: "muapi-flux-kontext-pro-t2i",
    providerId: "muapi",
    logicalFamily: "flux-kontext-t2i",
    modelId: "flux-kontext-pro-t2i",
    endpointId: "flux-kontext-pro-t2i",
    operation: "image_generation",
    modality: "image",
    capabilities: [CAPABILITIES.IMAGE_GENERATION, CAPABILITIES.COMMERCIAL_LICENSE],
    tier: "pro",
    variant: { familyTier: "pro" },
    pricing: { currency: "USD", unit: "generation", unitPrice: 0.03 },
    source: MUAPI_CATALOG_SOURCE,
    verification: verified("Text-to-Image", "Flux Kontext tiers are represented as one logical family."),
  },
  {
    id: "muapi-flux-kontext-max-t2i",
    providerId: "muapi",
    logicalFamily: "flux-kontext-t2i",
    modelId: "flux-kontext-max-t2i",
    endpointId: "flux-kontext-max-t2i",
    operation: "image_generation",
    modality: "image",
    capabilities: [CAPABILITIES.IMAGE_GENERATION, CAPABILITIES.COMMERCIAL_LICENSE],
    tier: "max",
    variant: { familyTier: "max" },
    pricing: { currency: "USD", unit: "generation", unitPrice: 0.06 },
    source: MUAPI_CATALOG_SOURCE,
    verification: verified("Text-to-Image", "Flux Kontext tiers are represented as one logical family."),
  },
  {
    id: "muapi-veo3-image-to-video",
    providerId: "muapi",
    logicalFamily: "veo-image-to-video",
    modelId: "veo3-image-to-video",
    endpointId: "veo3-image-to-video",
    operation: "image_to_video",
    modality: "video",
    capabilities: [CAPABILITIES.VIDEO_GENERATION, CAPABILITIES.COMMERCIAL_LICENSE],
    tier: "standard",
    variant: { generation: "veo3" },
    pricing: { currency: "USD", unit: "generation", unitPrice: 2.5 },
    source: MUAPI_CATALOG_SOURCE,
    verification: verified("Image-to-Video"),
  },
  {
    id: "muapi-veo31-image-to-video",
    providerId: "muapi",
    logicalFamily: "veo-image-to-video",
    modelId: "veo3.1-image-to-video",
    endpointId: "veo3.1-image-to-video",
    operation: "image_to_video",
    modality: "video",
    capabilities: [CAPABILITIES.VIDEO_GENERATION, CAPABILITIES.COMMERCIAL_LICENSE],
    tier: "standard",
    variant: { generation: "veo3.1" },
    pricing: { currency: "USD", unit: "generation", unitPrice: 2.5 },
    source: MUAPI_CATALOG_SOURCE,
    verification: verified("Image-to-Video"),
  },
  {
    id: "muapi-seedance-25-image-to-video-family",
    providerId: "muapi",
    logicalFamily: "seedance-2.5-image-to-video",
    modelId: null,
    endpointId: null,
    operation: "image_to_video",
    modality: "video",
    capabilities: [CAPABILITIES.VIDEO_GENERATION, CAPABILITIES.COMMERCIAL_LICENSE],
    tier: "parameterized",
    variant: { parameterized: ["resolution"] },
    resolution: { values: ["480p", "720p", "1080p", "4K"] },
    pricing: {
      currency: "USD",
      unit: "generation",
      unitPrice: null,
      rule: {
        type: "lookup",
        parameter: "resolution",
        values: { "480p": 0.85, "720p": 1.7, "1080p": 4.25, "4K": 8.5 },
      },
    },
    source: MUAPI_CATALOG_SOURCE,
    verification: verified("High-level shape of the catalog", "Family pricing is verified; concrete endpoint IDs are intentionally not invented from the wildcard catalog notation."),
  },
]);

export function registerProductionCapabilities({ capabilities = capabilityRegistry, deployments = providerCapabilityRegistry } = {}) {
  PRODUCTION_CAPABILITIES.forEach((definition) => capabilities.register(definition));
  PRODUCTION_DEPLOYMENTS.forEach((deployment) => deployments.register(deployment));
  if (typeof deployments.registerModel === "function") {
    MUAPI_MODEL_FIXTURES.forEach((model) => deployments.registerModel(model));
  }
  return { capabilities: PRODUCTION_CAPABILITIES, deployments: PRODUCTION_DEPLOYMENTS, models: MUAPI_MODEL_FIXTURES };
}

registerProductionCapabilities();
