// AI Twin Studio — Twin generation prompts.
//
// Twin candidates and Twin Assets are generated by calling the same Image
// Studio pipeline used elsewhere in Creative OS (ImageStudioRuntime with a
// ProviderRegistry fallback). This module only *composes the prompts*; it has
// no I/O so it is unit-testable in node:test.

import { TWIN_ASSET_CATALOG, getTwinAssetType } from "./TwinProfile.js";
import { getSkill } from "../skills/index.js";

// Builds a compact creative-style clause from the twin's Creative Defaults
// (preferred Creative Skills). Skill vocabulary informs generation the same
// way the Creative Skills Engine would route them.
export function composeCreativeDefaults(creativeDefaults = []) {
  const uniqueIds = [...new Set(creativeDefaults || [])].slice(0, 6);
  if (!uniqueIds.length) return "";
  const clauses = [];
  for (const skillId of uniqueIds) {
    try {
      const skill = getSkill(skillId);
      const vocab = (skill.vocabulary || [])
        .slice(0, 3)
        .map((v) => v.concept)
        .filter(Boolean);
      clauses.push(`${skill.name}${vocab.length ? ` (${vocab.join(", ")})` : ""}`);
    } catch (err) {
      clauses.push(skillId);
    }
  }
  return clauses.length ? `Preferred creative style: ${clauses.join("; ")}.` : "";
}

export function buildTwinCandidatePrompt(twin) {
  const identity = twin?.identity || {};
  const parts = [
    "Professional AI avatar of the creator (digital twin).",
  ];
  if (identity.description) parts.push(identity.description);
  if (identity.creativeStyle) parts.push(`Creative style: ${identity.creativeStyle}.`);
  if (identity.visualPreferences) parts.push(`Visual preferences: ${identity.visualPreferences}.`);
  if (identity.tone) parts.push(`Expression/tone: ${identity.tone}.`);
  const defaults = composeCreativeDefaults(twin?.creativeDefaults);
  if (defaults) parts.push(defaults);
  parts.push(
    "Preserve the exact likeness, facial features, and identity of the reference image.",
    "High detail, studio quality, natural skin texture, consistent identity across all outputs.",
  );
  return parts.join(" ");
}

export function buildTwinAssetPrompt(twin, assetTypeId) {
  const assetType = getTwinAssetType(assetTypeId) || {
    id: assetTypeId,
    label: "Twin Asset",
    aspectRatio: "3:4",
  };
  const base = buildTwinCandidatePrompt(twin);
  return `${base} ${assetType.label}: ${assetType.description}`.trim();
}

export function buildTwinAssetPromptMatrix(twin) {
  return TWIN_ASSET_CATALOG.map((assetType) => ({
    ...assetType,
    prompt: buildTwinAssetPrompt(twin, assetType.id),
  }));
}
